# Generated by Django 5.1.7 on 2025-04-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
